In [2]:
import numpy as np
import time

In [2]:
a = np.zeros((4, 2, 2))
a[0, :, :] = np.ones((2, 2))
a[1, :, :] = np.ones((2, 2)) * 2
a[2, :, :] = np.ones((2, 2)) * 3

In [3]:
print(a)

[[[1. 1.]
  [1. 1.]]

 [[2. 2.]
  [2. 2.]]

 [[3. 3.]
  [3. 3.]]

 [[0. 0.]
  [0. 0.]]]


In [4]:
a2 = a.reshape(-1, 2*2).T

In [5]:
print(a2)

[[1. 2. 3. 0.]
 [1. 2. 3. 0.]
 [1. 2. 3. 0.]
 [1. 2. 3. 0.]]


In [6]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
a[:, [3, 2, 1]]

array([[3, 2, 1],
       [8, 7, 6]])

In [8]:
np.round(10.255)

10.0

In [9]:
start = time.time()
for i in range(300000):
    pass
end = time.time()

print(end - start)

0.005815744400024414


In [12]:
for x in range(0, 100, 10):
    print(x)

0
10
20
30
40
50
60
70
80
90


In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a[5:0:-1]

array([5, 4, 3, 2, 1])